services:
  valkey:
    image: valkey/valkey:7-alpine
    container_name: claude-orchestrator-valkey
    ports:
      - '6379:6379'
    volumes:
      - valkey-data:/data
    command: valkey-server --appendonly yes

volumes:
  valkey-data: